#!/bin/sh /etc/rc.common

START=99

start() {
    logger  "开机运行脚本" "运行最大分区根目录start.sh"
    logger  "开机运行脚本" "Finding the largest partition in /mnt..."
    # 找到 /mnt 下最大的分区
    LARGEST_PARTITION=$(ls -1 /mnt | xargs -I {} du -s /mnt/{} | sort -nr | head -n 1 | awk '{print $2}')
    
    if [ -z "$LARGEST_PARTITION" ]; then
        logger  "开机运行脚本" "No partitions found in /mnt."
        return 1
    fi

    logger  "开机运行脚本" "Largest partition found: $LARGEST_PARTITION"
    # 检查是否存在 start.sh 脚本
    START_SCRIPT="$LARGEST_PARTITION/start.sh"
    if [ -f "$START_SCRIPT" ] && [ -x "$START_SCRIPT" ]; then
        logger  "开机运行脚本" "Running $START_SCRIPT..."
        $START_SCRIPT
    else
        logger  "开机运行脚本" " 未找到 start.sh not found or not executable in $LARGEST_PARTITION."
    fi
}

stop() {
    logger  "开机运行脚本" "Stopping my script..."
    # 在这里添加你的停止命令
}
